name: CI
run-name: ${{github.actor}} is running ${{github.workflow}} on ${{github.repository}}

on:
  pull_request: # On a pull request in the workflow's repository occurs
  workflow_call: # Indicate that a workflow can be called by another workflow
  workflow_dispatch: # Manually trigger a workflow run

jobs:
  test:
    name: Test with Node.js v${{matrix.node}} on ${{matrix.os}}
    strategy:
      matrix:
        os:
          # - macos-latest
          - ubuntu-latest
          # - windows-latest
        node:
          # See https://github.com/nodejs/release#release-schedule for details
          - 18.x # Maintenance
          - 20.x # LTS
          - 21.x # Current
    runs-on: ${{matrix.os}}
    steps:
    - name: â˜ï¸ - Checkout
      uses: actions/checkout@v4
    - name: ğŸ”§ - Use Node.js v${{matrix.node}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.node}}
        cache: npm
    - name: ğŸ“¦ - Run "npm ci"
      run: npm ci
    - name: ğŸ—ï¸ - Run "npm run build"
      run: npm run build --if-present
    - name: ğŸ§ª - Run "npm test"
      run: npm test
